version: '3'
services:
    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongo-data:/data/db
        networks:
          - shared-network

networks:
  shared-network:
    external: true

volumes:
  mongo-data:
    external: true
